version: 2
updates:
  - package-ecosystem: gomod
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
    allow:
      - dependency-type: direct
    target-branch: "main"
    directory: /
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    ignore:
      - update-types:
          - version-update:semver-major
    groups:
      golang-extensions:
        patterns:
          - "golang.org/x/*"