name: Create/Release Docker Image
on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v6
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: wisdom-oss/actions/docker-build/multiplatform/build.yml@main
        name: 
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          cache-key: ${{ runner.os }}-cache-${{ hashFiles('**/go.sum') }}
          cache-path: go-mod-build
          cache-map: |
            {
              "go-mod-build": "/root/.cache/go-build"
            }

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: wisdom-oss/actions/docker-build/multiplatform/merge.yml@main
        name: 
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}