name: Create/Release Docker Image
on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: wisdom-oss/actions/docker-build@main
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          cache-key: ${{ runner.os }}-cache-${{ hashFiles('**/go.sum') }}
          cache-path: go-mod-build
          cache-map: |
            {
              "go-mod-build": "/root/.cache/go-build"
            }